# Generated by Django 4.1.1 on 2022-09-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(help_text='Maqola nomini kiriting.....', max_length=200)),
                ('rasm', models.ImageField(upload_to='post_image')),
                ('maqola_soni', models.CharField(help_text='Maqola sonini kiriting.....', max_length=100)),
                ('batafsil', models.TextField(help_text="Maqola haqida umumiy ma'lumot")),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
    ]
